In [1]:
import numpy as np

arr = np.arange(1,9)

In [8]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
lista = [1,2,3,4,5,6,7,8]

In [2]:
arr.shape = (2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr + arr #adicion

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [10]:
lista + lista

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
arr - arr #sustraccion

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
arr * arr #producto

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [6]:
arr ** arr #exponencial

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [7]:
arr/arr #division

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])