In [1]:
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[52, 88, 30, 79],
       [70, 21,  7, 23],
       [28,  7, 75,  0]])

In [2]:
arr_ent.astype(float)

array([[52., 88., 30., 79.],
       [70., 21.,  7., 23.],
       [28.,  7., 75.,  0.]])

In [3]:
arr_ent

array([[52, 88, 30, 79],
       [70, 21,  7, 23],
       [28,  7, 75,  0]])

In [4]:
arr_ent.sort()
arr_ent

array([[30, 52, 79, 88],
       [ 7, 21, 23, 70],
       [ 0,  7, 28, 75]])

In [5]:
arr_ent.sort(axis=0)
arr_ent

array([[ 0,  7, 23, 70],
       [ 7, 21, 28, 75],
       [30, 52, 79, 88]])

In [6]:
arr_ent

array([[ 0,  7, 23, 70],
       [ 7, 21, 28, 75],
       [30, 52, 79, 88]])

In [11]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 0,  7, 23],
       [70,  7, 21],
       [28, 75, 30],
       [52, 79, 88]])

In [12]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 0  7 23]
 [70  7 21]
 [28 75 30]
 [52 79 88]]
[ 0  7 23 70  7 21 28 75 30 52 79 88]


In [13]:
lista_arr = plano_arr.tolist()
lista_arr
type(lista_arr)

list

In [14]:
arrays = np.split(arr_ent,4)
arrays

[array([[ 0,  7, 23]]),
 array([[70,  7, 21]]),
 array([[28, 75, 30]]),
 array([[52, 79, 88]])]

In [15]:
np.concatenate((arrays[1],arrays[0]),axis=0)

array([[70,  7, 21],
       [ 0,  7, 23]])

In [17]:
arr_ent

array([[ 5, 12],
       [45, 67],
       [24, 42],
       [54, 77],
       [37, 48],
       [93, 94]])

In [16]:
t_arr = arr_ent.T
t_arr

array([[ 5, 45, 24, 54, 37, 93],
       [12, 67, 42, 77, 48, 94]])